### PR TITLE
Give Twitter uploads a filename tweepy can type (fixes #117)

### LINKED ISSUE #117: Twitter posting crashes on Python 3.13: media_upload gets a None MIME type from extensionless filename
Reported by @mig5 in https://github.com/freedomofpress/trackthenews/pull/83#issuecomment-4677387357 and confirmed as a regression in https://github.com/freedomofpress/trackthenews/pull/83#issuecomment-5073551833.

Any article that matches the matchlist crashes the whole run as soon as it tries to post to Twitter:

```
Got one!
Traceback (most recent call last):
  File ".../bin/trackthenews", line 6, in <module>
    sys.exit(main())
  File ".../trackthenews/core.py", line 679, in main
    article.tweet()
  File ".../trackthenews/core.py", line 133, in tweet
    media = upload_twitter_images(img_files)
  File ".../trackthenews/core.py", line 228, in upload_twitter_images
    res = twitter.media_upload(filename="image", file=img)
  File ".../site-packages/tweepy/api.py", line 3488, in media_upload
    if chunked or file_type.startswith('video/'):
                  ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'startswith'
```

This only reproduces when Twitter is configured, which is why it was initially hard to pin down — with a Mastodon-only config the run never reaches `upload_twitter_images`.

## Root cause

`upload_twitter_images()` calls `media_upload()` with an extensionless filename:

```python
res = twitter.media_upload(filename="image", file=img)
```

Tweepy has to derive a MIME type from that call, and how it does so changed underneath us in #83 (Python 3.11 + tweepy 4.14 → Python 3.13 + tweepy 4.17).

**Before:** tweepy 4.14 used `imghdr` to sniff the first 32 bytes of the file object, so the missing extension didn't matter — it saw the JPEG magic bytes and returned `image/jpeg`:

```python
file_type = imghdr.what(filename, h=h)
if file_type is not None:
    file_type = 'image/' + file_type
```

**After:** `imghdr` was removed from the stdlib in Python 3.13. Tweepy 4.17 handles that by falling back to `mimetypes.guess_type()`, which looks *only* at the filename:

```python
file_type = None
try:
    import imghdr
except ModuleNotFoundError:
    # imghdr was removed in Python 3.13
    pass
else:
    ...
if file_type is None:
    file_type = mimetypes.guess_type(filename)[0]

if chunked or file_type.startswith('video/'):   # <-- file_type is None
```

`mimetypes.guess_type("image")` returns `(None, None)` because `"image"` has no extension, so `file_type` is `None` and the `.startswith()` call blows up. Content sniffing is gone; the filename is now the only signal, and ours carries no information.

Note this is not fixable by pinning tweepy — tweepy 4.14 does `import imghdr` at module scope, so it can't even be imported on Python 3.13. The filename is ours to fix.

## Proposed fix

Pass a filename with an extension that matches what `prepare_images()` actually produces (`img.save(img_io, format="jpeg")`), so `mimetypes.guess_type()` resolves to `image/jpeg`. The filename is only used for MIME detection and as the multipart part name, so this is safe.

While we're here, `upload_twitter_images()` swallows `TweepyException` per image but nothing guards against a non-Tweepy failure like this one, and a crash mid-post takes down the entire run (see #114). Worth at least making the failure mode of this function not depend on tweepy's internal type detection succeeding.

## Acceptance criteria

- [ ] A matched article posts to Twitter successfully on Python 3.13 / tweepy 4.17.
- [ ] Regression test covering the MIME type actually handed to tweepy, so a future tweepy change to type detection fails in CI instead of in production.

### PR DESCRIPTION
**Pull request by harrislapiroff**
Fixes #117. Confirms @mig5's report on #83 as a real regression and fixes it.

## The bug

Every run that matched an article died as soon as it tried to post to Twitter:

```
Got one!
  File ".../trackthenews/core.py", line 228, in upload_twitter_images
    res = twitter.media_upload(filename="image", file=img)
  File ".../tweepy/api.py", line 3488, in media_upload
    if chunked or file_type.startswith('video/'):
                  ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'startswith'
```

`upload_twitter_images()` passed `filename="image"` — no extension. That was harmless while tweepy 4.14 determined the MIME type by sniffing the file's magic bytes:

```python
file_type = imghdr.what(filename, h=h)   # h = first 32 bytes of the file
```

Python 3.13 removed `imghdr` from the stdlib. Tweepy 4.17 handles that by falling back to `mimetypes.guess_type()`, which looks only at the filename:

```python
if file_type is None:
    file_type = mimetypes.guess_type(filename)[0]

if chunked or file_type.startswith('video/'):   # file_type is None
```

`mimetypes.guess_type("image")` is `(None, None)`, so tweepy dereferences `None` while deciding whether the file is a video. Content sniffing is gone and the filename is now the only signal — ours carried no information.

Worth noting this isn't fixable by pinning tweepy: 4.14 does `import imghdr` at module scope, so it can't be imported on 3.13 at all. The filename is ours to fix.

## The fix

Name the file `image.jpeg`, and derive the filename, the PIL save format, and the Mastodon `mime_type` from one `IMAGE_FORMAT` constant so they can't drift apart:

```python
IMAGE_FORMAT = "jpeg"
IMAGE_FILENAME = f"image.{IMAGE_FORMAT}"
IMAGE_MIME_TYPE = f"image/{IMAGE_FORMAT}"
```

Previously the format lived in three unconnected string literals (`format="jpeg"` in `prepare_images`, `"image"` in `upload_twitter_images`, `"image/jpeg"` in `toot`), which is how they were able to disagree in the first place.

## Tests

This repo had no test suite, so this adds pytest, a `tests/` directory, and a CI job to run it (a small down payment on #54).

The tests that matter here drive tweepy's **real** `media_upload()` with only the outbound HTTP request stubbed, rather than asserting on a mock's call args. That's deliberate: running tweepy's actual type-detection code is what makes these regression tests. Verified they reproduce the reported failure — against the unfixed line they fail with the original `AttributeError` at the same `api.py:3488`:

```
FAILED tests/test_media_upload.py::test_upload_twitter_images_posts_each_image
  - AttributeError: 'NoneType' object has no attribute 'startswith'
FAILED tests/test_media_upload.py::test_upload_twitter_images_skips_images_the_api_rejects
  - AttributeError: 'NoneType' object has no attribute 'startswith'
```

and pass with it. Coverage: rendered bytes really are the format `IMAGE_FORMAT` claims; the filename resolves to `image/jpeg` via `mimetypes`; uploads reach the simple (non-chunked) endpoint; `tweet()` works end to end from the crash site in the traceback; an image the API rejects doesn't cost the rest of the post; and Twitter-not-configured still short-circuits.

`ruff check`, `ruff format --check`, and `pytest` (6 passed) are all green locally on Python 3.13.

## Note on the earlier confusion

In the comparison run on #83, `0aafab4` printed "Twitter is not configured. Skipping tweet." — that config difference is incidental, not part of the bug. The regression is real on its own terms: `imghdr` sniffing worked on 3.11/tweepy 4.14 and there is no sniffing at all on 3.13/tweepy 4.17.

## Not addressed here

A failure during posting still aborts the whole run rather than being contained to one article/platform — that's #114 and wants its own change.

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

**Comment by harrislapiroff** [comment]
This PR may need some massaging, but I've given it a human review and the approach seems reasonable. Attn @freedomofpress/fpf-infra I think we should get this in before releasing the upgrades. I will be PTO this week, though, so someone else will need to shepherd it to completion. (In general I was also not able to test Twitter end-to-end, my API key never returned anything but a 403 under both new and old code, but I was able to confirm Mastodon worked. Someone will want to watch the @foiafeed Twitter account carefully.)

**Review by mig5 — APPROVED** [review]
Looks like a simple fix! Thanks!

I'm going to merge it and attempt to release it through to Pypi and we'll monitor on the existing foiafeed instance (and the X account).

Assuming it's all fine, then we'll try and migrate trackthenews to the Debian 13 foiafeed instance.
